services:
  db:
    image: postgres:18.1-trixie
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - "./docker-entrypoint.initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password

